spring.application.name=greenops

# SQL Server
spring.datasource.url=jdbc:sqlserver://ACER-LAP:1433;databaseName=GreenopsDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=Kabilan
spring.datasource.password=Kabilan@7305
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JWT
jwt.secret=GreenOpsJWTSecretKey2026ProductionSecureKey123456789
jwt.expiration=3600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT:
# Preserve the existing database names
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Server
server.port=8080